unique_ids:
  assets:
    standard-page.html: PYTRMVOPPVNOGLDUH2VTOE6FHVSBKVA6
    theme.css: L56YW6ZATXKT4WNOUJXS3NYBYZZQMFSP
  forms:
    Form1: GOFDN6GXVEH2ZW4JBKBDG5DCYDBLUZVX
  modules: {}
  scripts: {}
  server_modules: {}
